apiVersion: qonductor.io/v1
kind: HybridWorkflow
metadata:
  name: qaoa-12-iter5
  namespace: default
  labels:
    app: qonductor
    algorithm: qaoa
spec:
  workflowImageRef: 9b8ede160090
  priority: balanced
  maxRetries: 3
  containers:
  - name: qaoa-spsa-driver
    image: qonductor-operator:latest
    resources:
      limits:
        cpu: '1'
        memory: 2Gi
  scheduling:
    classicalPolicy: FilterScore
    quantumPolicy: NSGA2
    schedulingInterval: 120
    schedulingThreshold: 1
  errorMitigation:
    enabled: false
    stackedTechniques: []
  workflowInputs:
    qaoa:
      logicalCircuitId: qaoa_indep_qiskit_12
      circuitQasm: "OPENQASM 3.0;\ninclude \"stdgates.inc\";\ninput float[64] _b_0_;\n\
        input float[64] _b_1_;\ninput float[64] _g_0_;\ninput float[64] _g_1_;\ngate\
        \ rzz(p0) _gate_q_0, _gate_q_1 {\n  cx _gate_q_0, _gate_q_1;\n  rz(p0) _gate_q_1;\n\
        \  cx _gate_q_0, _gate_q_1;\n}\nbit[12] meas;\nqubit[12] q;\nh q[0];\nh q[1];\n\
        h q[2];\nh q[3];\nh q[4];\nh q[5];\nh q[6];\nh q[7];\nh q[8];\nh q[9];\nh\
        \ q[10];\nh q[11];\nrzz(2*_g_0_) q[0], q[1];\nrzz(2*_g_0_) q[0], q[4];\nrzz(2*_g_0_)\
        \ q[0], q[5];\nrzz(2*_g_0_) q[0], q[6];\nrzz(2*_g_0_) q[0], q[8];\nrzz(2*_g_0_)\
        \ q[0], q[9];\nrzz(2*_g_0_) q[1], q[3];\nrzz(2*_g_0_) q[1], q[6];\nrzz(2*_g_0_)\
        \ q[1], q[7];\nrzz(2*_g_0_) q[1], q[9];\nrzz(2*_g_0_) q[2], q[3];\nrzz(2*_g_0_)\
        \ q[2], q[4];\nrzz(2*_g_0_) q[2], q[5];\nrzz(2*_g_0_) q[2], q[7];\nrzz(2*_g_0_)\
        \ q[2], q[8];\nrzz(2*_g_0_) q[2], q[10];\nrzz(2*_g_0_) q[2], q[11];\nrzz(2*_g_0_)\
        \ q[3], q[4];\nrzz(2*_g_0_) q[3], q[7];\nrzz(2*_g_0_) q[3], q[8];\nrzz(2*_g_0_)\
        \ q[3], q[11];\nrzz(2*_g_0_) q[4], q[6];\nrzz(2*_g_0_) q[4], q[7];\nrzz(2*_g_0_)\
        \ q[4], q[10];\nrzz(2*_g_0_) q[4], q[11];\nrzz(2*_g_0_) q[5], q[7];\nrzz(2*_g_0_)\
        \ q[5], q[10];\nrzz(2*_g_0_) q[6], q[7];\nrzz(2*_g_0_) q[6], q[8];\nrzz(2*_g_0_)\
        \ q[6], q[9];\nrzz(2*_g_0_) q[6], q[11];\nrzz(2*_g_0_) q[7], q[9];\nrzz(2*_g_0_)\
        \ q[7], q[10];\nrzz(2*_g_0_) q[8], q[9];\nrzz(2*_g_0_) q[8], q[10];\nrzz(2*_g_0_)\
        \ q[8], q[11];\nrx(2*_b_0_) q[0];\nrx(2*_b_0_) q[1];\nrx(2*_b_0_) q[2];\n\
        rx(2*_b_0_) q[3];\nrx(2*_b_0_) q[4];\nrx(2*_b_0_) q[5];\nrx(2*_b_0_) q[6];\n\
        rx(2*_b_0_) q[7];\nrx(2*_b_0_) q[8];\nrx(2*_b_0_) q[9];\nrx(2*_b_0_) q[10];\n\
        rx(2*_b_0_) q[11];\nrzz(2*_g_1_) q[0], q[1];\nrzz(2*_g_1_) q[0], q[4];\nrzz(2*_g_1_)\
        \ q[0], q[5];\nrzz(2*_g_1_) q[0], q[6];\nrzz(2*_g_1_) q[0], q[8];\nrzz(2*_g_1_)\
        \ q[0], q[9];\nrzz(2*_g_1_) q[1], q[3];\nrzz(2*_g_1_) q[1], q[6];\nrzz(2*_g_1_)\
        \ q[1], q[7];\nrzz(2*_g_1_) q[1], q[9];\nrzz(2*_g_1_) q[2], q[3];\nrzz(2*_g_1_)\
        \ q[2], q[4];\nrzz(2*_g_1_) q[2], q[5];\nrzz(2*_g_1_) q[2], q[7];\nrzz(2*_g_1_)\
        \ q[2], q[8];\nrzz(2*_g_1_) q[2], q[10];\nrzz(2*_g_1_) q[2], q[11];\nrzz(2*_g_1_)\
        \ q[3], q[4];\nrzz(2*_g_1_) q[3], q[7];\nrzz(2*_g_1_) q[3], q[8];\nrzz(2*_g_1_)\
        \ q[3], q[11];\nrzz(2*_g_1_) q[4], q[6];\nrzz(2*_g_1_) q[4], q[7];\nrzz(2*_g_1_)\
        \ q[4], q[10];\nrzz(2*_g_1_) q[4], q[11];\nrzz(2*_g_1_) q[5], q[7];\nrzz(2*_g_1_)\
        \ q[5], q[10];\nrzz(2*_g_1_) q[6], q[7];\nrzz(2*_g_1_) q[6], q[8];\nrzz(2*_g_1_)\
        \ q[6], q[9];\nrzz(2*_g_1_) q[6], q[11];\nrzz(2*_g_1_) q[7], q[9];\nrzz(2*_g_1_)\
        \ q[7], q[10];\nrzz(2*_g_1_) q[8], q[9];\nrzz(2*_g_1_) q[8], q[10];\nrzz(2*_g_1_)\
        \ q[8], q[11];\nrx(2*_b_1_) q[0];\nrx(2*_b_1_) q[1];\nrx(2*_b_1_) q[2];\n\
        rx(2*_b_1_) q[3];\nrx(2*_b_1_) q[4];\nrx(2*_b_1_) q[5];\nrx(2*_b_1_) q[6];\n\
        rx(2*_b_1_) q[7];\nrx(2*_b_1_) q[8];\nrx(2*_b_1_) q[9];\nrx(2*_b_1_) q[10];\n\
        rx(2*_b_1_) q[11];\nbarrier q[0], q[1], q[2], q[3], q[4], q[5], q[6], q[7],\
        \ q[8], q[9], q[10], q[11];\nmeas[0] = measure q[0];\nmeas[1] = measure q[1];\n\
        meas[2] = measure q[2];\nmeas[3] = measure q[3];\nmeas[4] = measure q[4];\n\
        meas[5] = measure q[5];\nmeas[6] = measure q[6];\nmeas[7] = measure q[7];\n\
        meas[8] = measure q[8];\nmeas[9] = measure q[9];\nmeas[10] = measure q[10];\n\
        meas[11] = measure q[11];\n"
      circuitFormat: qasm3
      parameterNames:
      - _b_0_
      - _b_1_
      - _g_0_
      - _g_1_
      parameterCount: 4
      qubits: 12
      clbits: 12
      shots: 128
      maxIterations: 5
      priority: balanced
      edges:
      - - 0
        - 1
      - - 0
        - 4
      - - 0
        - 5
      - - 0
        - 6
      - - 0
        - 8
      - - 0
        - 9
      - - 1
        - 3
      - - 1
        - 6
      - - 1
        - 7
      - - 1
        - 9
      - - 2
        - 3
      - - 2
        - 4
      - - 2
        - 5
      - - 2
        - 7
      - - 2
        - 8
      - - 2
        - 10
      - - 2
        - 11
      - - 3
        - 4
      - - 3
        - 7
      - - 3
        - 8
      - - 3
        - 11
      - - 4
        - 6
      - - 4
        - 7
      - - 4
        - 10
      - - 4
        - 11
      - - 5
        - 7
      - - 5
        - 10
      - - 6
        - 7
      - - 6
        - 8
      - - 6
        - 9
      - - 6
        - 11
      - - 7
        - 9
      - - 7
        - 10
      - - 8
        - 9
      - - 8
        - 10
      - - 8
        - 11
      seed: 12345
      source:
        workloadDir: /home/reol/Qonductor-SC25/workload_python/quantum_approximation_optimization_algorithm_qaoa
        spec: /home/reol/Qonductor-SC25/workload_python/quantum_approximation_optimization_algorithm_qaoa/spec_12.json
        parameters: /home/reol/Qonductor-SC25/workload_python/quantum_approximation_optimization_algorithm_qaoa/parameters_12.json
