apiVersion: qonductor.io/v1
kind: HybridWorkflow
metadata:
  name: grover-v-chain-dbcheck-2-20260722-01
  namespace: default
  labels:
    app: qonductor
    algorithm: grover-v-chain
    converted_from: qslurm_workloads
spec:
  workflowImageRef: 'cbe07a2a7ae9'
  priority: balanced
  maxRetries: 3
  containers: []
  scheduling:
    classicalPolicy: FilterScore
    quantumPolicy: NSGA2
    schedulingInterval: 30
    schedulingThreshold: 1
  errorMitigation:
    enabled: false
    stackedTechniques: []
  workflowInputs:
    quantum:
      logicalCircuitId: grover-noancilla_indep_qiskit_2
      qasmPath: /home/reol/Qonductor-SC25/workflow/pure_quantum/grover_v_chain/grover-v-chain_indep_qiskit_2.qasm3
      circuitQasm: 'OPENQASM 3.0;

        include "stdgates.inc";

        bit[2] meas;

        qubit[1] q;

        qubit[1] flag;

        rz(pi/2) q[0];

        sx q[0];

        rz(pi/2) q[0];

        x flag[0];

        barrier q[0], flag[0];

        meas[0] = measure q[0];

        meas[1] = measure flag[0];

        '
      circuitFormat: qasm3
      qubits: 2
      shots: 1024
      priority: balanced
      source:
        qslurmSource: qslurm_workloads/pure_quantum/grover_v_chain/spec_2.json
        workloadDir: /home/reol/Qonductor-SC25/workflow/pure_quantum/grover_v_chain
        spec: /home/reol/Qonductor-SC25/workflow/pure_quantum/grover_v_chain/spec_2.json
