apiVersion: qonductor.io/v1
kind: HybridWorkflow
metadata:
  name: pq-036-quantum-phase-estimation-qpe-exact-2-20260722152725-a057
  namespace: default
  labels:
    app: qonductor
    algorithm: quantum-phase-estimation-qpe-exact
    converted_from: qslurm_workloads
spec:
  workflowImageRef: '235e58bc61b9'
  priority: balanced
  maxRetries: 3
  containers: []
  scheduling:
    classicalPolicy: FilterScore
    quantumPolicy: NSGA2
    schedulingInterval: 30
    schedulingThreshold: 1
  errorMitigation:
    enabled: false
    stackedTechniques: []
  workflowInputs:
    quantum:
      logicalCircuitId: qpeexact_indep_qiskit_2
      qasmPath: /home/reol/Qonductor-SC25/workflow/pure_quantum/quantum_phase_estimation_qpe_exact/qpeexact_indep_qiskit_2.qasm3
      circuitQasm: '// Benchmark was created by MQT Bench on 2024-03-18

        // For more information about MQT Bench, please visit https://www.cda.cit.tum.de/mqtbench/

        // MQT Bench version: 1.1.0

        // Qiskit version: 1.0.2

        // Used Gate Set: [''id'', ''rz'', ''sx'', ''x'', ''cx'', ''measure'', ''barrier'']


        OPENQASM 3.0;

        include "stdgates.inc";

        qubit[1] q;

        qubit[1] psi;

        bit[1] c;

        rz(pi/2) q[0];

        sx q[0];

        rz(pi/2) q[0];

        x psi[0];

        rz(pi/2) psi[0];

        cx psi[0],q[0];

        rz(-pi/2) q[0];

        cx psi[0],q[0];

        rz(-pi) q[0];

        sx q[0];

        rz(pi/2) q[0];

        barrier q[0],psi[0];

        c[0] = measure q[0];

        '
      circuitFormat: qasm3
      qubits: 2
      shots: 1024
      priority: balanced
      source:
        qslurmSource: qslurm_workloads/pure_quantum/quantum_phase_estimation_qpe_exact/spec_2.json
        workloadDir: /home/reol/Qonductor-SC25/workflow/pure_quantum/quantum_phase_estimation_qpe_exact
        spec: /home/reol/Qonductor-SC25/workflow/pure_quantum/quantum_phase_estimation_qpe_exact/spec_2.json
