"""Runtime helpers for dynamically driven QAOA workflows.

The original Slurm workload uses two MPI ranks: a classical SPSA driver and
a quantum worker that calls ``q_exec``.  In Qonductor, the classical driver is
a normal K8s Job and each quantum evaluation becomes a runtime ``QuantumJob``
child resource.  The parent DAG therefore stays compact while the iterative
algorithm remains dynamic.
"""

from __future__ import annotations

import http.server
import json
import math
import os
import random
import re
import sqlite3
import threading
import time
import uuid
from collections.abc import Iterator
from typing import Any

from src.operator.k8s_client import (
    K8sClient,
    QUANTUM_JOB_PLURAL,
    _resource_hash,
    _rfc1123_name,
)
from src.utils.logging_config import configure_logging

DEFAULT_QUANTUM_TIMEOUT_SECONDS = 21600.0
RESULT_CALLBACK_PATH = "/qonductor/quantum-result"

DEFAULT_QAOA_EDGES: tuple[tuple[int, int], ...] = (
    (0, 1), (0, 4), (0, 5), (0, 6), (0, 8), (0, 9),
    (1, 3), (1, 6), (1, 7), (1, 9),
    (2, 3), (2, 4), (2, 5), (2, 7), (2, 8), (2, 10), (2, 11),
    (3, 4), (3, 7), (3, 8), (3, 11),
    (4, 6), (4, 7), (4, 10), (4, 11),
    (5, 7), (5, 10),
    (6, 7), (6, 8), (6, 9), (6, 11),
    (7, 9), (7, 10),
    (8, 9), (8, 10), (8, 11),
)


def initialize_parameters(count: int) -> list[float]:
    return [0.05 * float((i % 11) + 1) for i in range(count)]


def legacy_c_random(seed: int) -> Iterator[float]:
    """Yield glibc rand() values normalized by RAND_MAX.

    The offline corpus was generated by the legacy C SPSA driver, so replay
    must use its deterministic perturbation stream instead of Python's RNG.
    """
    modulus = 2147483647
    state = [int(seed) % modulus]
    if state[0] == 0:
        state[0] = 1
    for _ in range(1, 31):
        state.append((16807 * state[-1]) % modulus)
    state.extend((state[0], state[1], state[2]))
    while len(state) < 344:
        index = len(state)
        state.append((state[index - 31] + state[index - 3]) & 0xFFFFFFFF)
    while True:
        index = len(state)
        value = (state[index - 31] + state[index - 3]) & 0xFFFFFFFF
        state.append(value)
        yield float(value >> 1) / float(modulus)


def quantum_job_assigned_qpu(client: K8sClient, name: str) -> str:
    quantum_job = client.get_cr(QUANTUM_JOB_PLURAL, name)
    if not quantum_job:
        raise RuntimeError(f"QuantumJob {name!r} disappeared")
    assigned_qpu = quantum_job.get("status", {}).get("assignedQPU", "")
    if not assigned_qpu or assigned_qpu == "none":
        raise RuntimeError(f"QuantumJob {name!r} completed without an assigned QPU")
    return assigned_qpu


def _env_enabled(name: str, default: str = "1") -> bool:
    value = os.environ.get(name, default).strip().lower()
    return value in {"1", "true", "yes", "on"}


class QuantumResultCallbackServer:
    """Small in-Pod callback endpoint used by dynamic classical drivers."""

    def __init__(self, *, advertised_host: str, port: int) -> None:
        self.advertised_host = advertised_host
        self.port = port
        self.token = uuid.uuid4().hex
        self.url = f"http://{advertised_host}:{port}{RESULT_CALLBACK_PATH}"
        self._condition = threading.Condition()
        self._statuses: dict[str, dict[str, Any]] = {}
        self.fallback_used = False
        self._server: http.server.ThreadingHTTPServer | None = None
        self._thread: threading.Thread | None = None

    @classmethod
    def from_env(cls, mode: str) -> "QuantumResultCallbackServer | None":
        if mode != "k8s" or not _env_enabled("QONDUCTOR_RESULT_CALLBACK_ENABLED"):
            return None
        advertised_host = os.environ.get("QONDUCTOR_DRIVER_CALLBACK_HOST", "").strip()
        if not advertised_host:
            return None
        port = int(os.environ.get("QONDUCTOR_DRIVER_CALLBACK_PORT", "9188"))
        server = cls(advertised_host=advertised_host, port=port)
        server.start()
        return server

    def start(self) -> None:
        if self._server is not None:
            return

        parent = self

        class Handler(http.server.BaseHTTPRequestHandler):
            def do_POST(self) -> None:
                if self.path != RESULT_CALLBACK_PATH:
                    self.send_response(404)
                    self.end_headers()
                    return
                if self.headers.get("X-Qonductor-Callback-Token", "") != parent.token:
                    self.send_response(403)
                    self.end_headers()
                    return
                try:
                    length = int(self.headers.get("Content-Length", "0") or "0")
                    payload = json.loads(self.rfile.read(length).decode("utf-8"))
                    quantum_job = str(payload.get("quantumJob") or "")
                    status = payload.get("status")
                    if not quantum_job or not isinstance(status, dict):
                        raise ValueError("callback payload requires quantumJob and status")
                except Exception as exc:
                    self.send_response(400)
                    self.end_headers()
                    self.wfile.write(str(exc).encode("utf-8"))
                    return

                with parent._condition:
                    parent._statuses[quantum_job] = status
                    parent._condition.notify_all()
                self.send_response(204)
                self.end_headers()

            def log_message(self, format: str, *args: Any) -> None:
                return

        self._server = http.server.ThreadingHTTPServer(("0.0.0.0", self.port), Handler)
        self._thread = threading.Thread(target=self._server.serve_forever, daemon=True)
        self._thread.start()

    def wait_for_status(self, name: str, timeout_s: float) -> dict[str, Any] | None:
        deadline = time.monotonic() + max(0.0, timeout_s)
        with self._condition:
            while name not in self._statuses:
                remaining = deadline - time.monotonic()
                if remaining <= 0:
                    return None
                self._condition.wait(timeout=remaining)
            return self._statuses.pop(name)

    def mark_fallback(self) -> None:
        self.fallback_used = True

    def close_after_fallback_drain(self) -> None:
        if self._server is None:
            return
        if self.fallback_used:
            drain_s = max(
                0.0,
                float(os.environ.get(
                    "QONDUCTOR_RESULT_CALLBACK_DRAIN_SECONDS",
                    "1.0",
                )),
            )
            if drain_s > 0:
                time.sleep(drain_s)
        self.close()

    def close(self) -> None:
        if self._server is None:
            return
        self._server.shutdown()
        self._server.server_close()
        self._server = None


def offline_parameter_pair(
    *,
    logical_id: str,
    qpu_name: str,
    iteration: int,
    parameter_names: list[str],
    shots: int,
) -> tuple[dict[str, float], dict[str, float]]:
    database_path = os.environ.get(
        "QONDUCTOR_OFFLINE_RESULTS_PATH",
        "/etc/qonductor/offline-results/quantum_offline_results.sqlite",
    )
    noise_model_version = os.environ.get(
        "QONDUCTOR_OFFLINE_NOISE_MODEL_VERSION",
        "qpu-json-depolarizing-readout-v1",
    )
    qpu_candidates = [qpu_name]
    match = re.match(r"^(qpu[a-z_]*\d+_\d+q)(?:-|$)", qpu_name)
    if match and match.group(1) not in qpu_candidates:
        qpu_candidates.append(match.group(1))
    # Fall back to qonductor_base_name from the QPU JSON profile when the
    # regex extraction fails (mirrors the executor's resolution order).
    if len(qpu_candidates) == 1:
        qpu_json_path = os.environ.get(
            "QPU_JSON_PATH",
            f"/etc/qonductor/qpus/{qpu_name}.json",
        )
        try:
            with open(qpu_json_path, encoding="utf-8") as fh:
                qpu_data = json.load(fh)
            base_name = str(
                qpu_data.get("qonductor_base_name")
                or qpu_data.get("offline_results_qpu_name")
                or ""
            )
            if base_name and base_name not in qpu_candidates:
                qpu_candidates.append(base_name)
        except (OSError, json.JSONDecodeError, KeyError):
            pass

    connection = sqlite3.connect(f"file:{database_path}?mode=ro", uri=True)
    try:
        rows = []
        for candidate in qpu_candidates:
            rows = connection.execute(
                """
                SELECT parameter_bindings_json
                FROM hardware_results
                WHERE logical_id = ?
                  AND qpu_name = ?
                  AND profile_version = 'v1'
                  AND shots = ?
                  AND noise_model_version = ?
                ORDER BY rowid
                LIMIT 2 OFFSET ?
                """,
                (
                    logical_id,
                    candidate,
                    shots,
                    noise_model_version,
                    2 * iteration,
                ),
            ).fetchall()
            if len(rows) == 2:
                break
    finally:
        connection.close()
    if len(rows) != 2:
        raise LookupError(
            "offline parameter pair not found for "
            f"logical_id={logical_id!r}, qpu={qpu_name!r}, "
            f"candidates={qpu_candidates!r}, shots={shots}, iteration={iteration}"
        )

    plus_bindings = json.loads(rows[0][0])
    minus_bindings = json.loads(rows[1][0])
    expected_names = set(parameter_names)
    for bindings in (plus_bindings, minus_bindings):
        if set(bindings) != expected_names:
            raise ValueError(
                "offline parameter names do not match the workflow circuit"
            )
    return plus_bindings, minus_bindings


def wrap_angles(theta: list[float]) -> list[float]:
    wrapped = []
    for value in theta:
        while value > math.pi:
            value -= 2.0 * math.pi
        while value < -math.pi:
            value += 2.0 * math.pi
        wrapped.append(value)
    return wrapped


def bitstring_cut_value(
    bitstring: str,
    edges: list[list[int]] | list[tuple[int, int]] | tuple[tuple[int, int], ...],
    bit_count: int | None = None,
) -> float:
    bits = "".join(ch for ch in bitstring if ch in "01")
    bit_count = bit_count or len(bits)
    if len(bits) != bit_count:
        raise ValueError(f"bitstring {bitstring!r} does not have {bit_count} bits")

    cut = 0.0
    for a, b in edges:
        # Preserve the same little-endian interpretation used by the C driver.
        if bits[bit_count - 1 - int(a)] != bits[bit_count - 1 - int(b)]:
            cut += 1.0
    return cut


def extract_counts(result_payload: Any) -> dict[str, int]:
    if isinstance(result_payload, str):
        result_payload = json.loads(result_payload)
    if not isinstance(result_payload, dict):
        raise ValueError("quantum result payload must be a dict or JSON object")
    if "counts" in result_payload:
        return {str(k): int(v) for k, v in result_payload["counts"].items()}
    results = result_payload.get("results")
    if isinstance(results, list) and results:
        counts = results[0].get("counts", {})
        return {str(k): int(v) for k, v in counts.items()}
    raise ValueError("quantum result payload does not contain counts")


def counts_average(
    result_payload: Any,
    edges: list[list[int]] | list[tuple[int, int]] | tuple[tuple[int, int], ...],
    bit_count: int,
) -> float:
    counts = extract_counts(result_payload)
    total = sum(counts.values())
    if total <= 0:
        return math.inf
    weighted_sum = sum(
        bitstring_cut_value(bitstring, edges, bit_count) * count
        for bitstring, count in counts.items()
    )
    return weighted_sum / float(total)


def submit_quantum_eval(
    client: K8sClient,
    *,
    workflow_ref: str,
    step_id: str,
    logical_circuit_id: str,
    circuit_qasm: str,
    parameter_bindings: dict[str, float],
    qubits: int,
    shots: int,
    priority: str,
    iteration: int,
    eval_label: str,
    preferred_qpu: str = "",
    result_callback: QuantumResultCallbackServer | None = None,
    namespace: str = "default",
) -> dict:
    name = _rfc1123_name(
        "qj",
        step_id,
        str(iteration),
        eval_label,
        f"{_resource_hash(workflow_ref)}-{uuid.uuid4().hex[:12]}",
    )
    body = {
        "apiVersion": "qonductor.io/v1",
        "kind": "QuantumJob",
        "metadata": {
            "name": name,
            "namespace": namespace,
            "labels": {
                "app": "qonductor",
                "workflow": workflow_ref,
                "step_id": step_id,
                "iteration": str(iteration),
                "eval_label": eval_label,
            },
        },
        "spec": {
            "workflowRef": workflow_ref,
            "stepId": f"{step_id}-{iteration}-{eval_label}",
            "label": f"{step_id}_{iteration}_{eval_label}",
            "qubits": qubits,
            "shots": shots,
            "priority": priority,
            "logicalCircuitId": logical_circuit_id,
            "circuitNames": [logical_circuit_id],
            "circuitQasm": circuit_qasm,
            "circuitFormat": "qasm3",
            "parameterBindings": parameter_bindings,
            "iteration": iteration,
            "evalLabel": eval_label,
        },
        "status": {"phase": "Pending"},
    }
    if result_callback is not None:
        body["metadata"]["annotations"] = {
            "qonductor.io/result-callback-url": result_callback.url,
            "qonductor.io/result-callback-token": result_callback.token,
        }
    if preferred_qpu:
        body["spec"]["preferredQPU"] = preferred_qpu
    return client.create_cr(QUANTUM_JOB_PLURAL, namespace=namespace, body=body)


def _result_from_quantum_status(
    name: str,
    status: dict[str, Any],
) -> tuple[bool, dict | None]:
    phase = status.get("phase", "")
    if phase == "Completed":
        result = status.get("result")
        if result is None:
            raise RuntimeError(f"QuantumJob {name!r} completed without result")
        return True, result
    if phase == "Failed":
        raise RuntimeError(f"QuantumJob {name!r} failed: {status}")
    return False, None


def wait_for_quantum_result(
    client: K8sClient,
    name: str,
    *,
    timeout_s: float = DEFAULT_QUANTUM_TIMEOUT_SECONDS,
    poll_s: float = 2.0,
    callback_server: QuantumResultCallbackServer | None = None,
) -> dict:
    deadline = time.monotonic() + timeout_s
    while time.monotonic() < deadline:
        if callback_server is not None:
            remaining = max(0.0, deadline - time.monotonic())
            fallback_poll_s = float(os.environ.get(
                "QONDUCTOR_RESULT_CALLBACK_FALLBACK_POLL_SECONDS",
                "30",
            ))
            status = callback_server.wait_for_status(
                name,
                timeout_s=min(fallback_poll_s, remaining),
            )
            if status is not None:
                done, result = _result_from_quantum_status(name, status)
                if done:
                    return result

        qj = client.get_cr(QUANTUM_JOB_PLURAL, name)
        if not qj:
            raise RuntimeError(f"QuantumJob {name!r} disappeared")
        done, result = _result_from_quantum_status(name, qj.get("status", {}))
        if done:
            if callback_server is not None:
                callback_server.mark_fallback()
            return result
        if callback_server is None:
            time.sleep(poll_s)
    raise TimeoutError(f"Timed out waiting for QuantumJob {name!r}")


def _load_runtime_config(config: dict[str, Any] | None = None) -> dict[str, Any]:
    if config is not None:
        return config.get("qaoa", config)
    raw = os.environ.get("QONDUCTOR_WORKFLOW_INPUTS", "{}")
    loaded = json.loads(raw or "{}")
    return loaded.get("qaoa", loaded)


def run_qaoa_spsa_driver(
    config: dict[str, Any] | None = None,
    client: K8sClient | None = None,
) -> dict[str, Any]:
    configure_logging()

    cfg = _load_runtime_config(config)
    mode = os.environ.get("QONDUCTOR_MODE", "k8s")
    namespace = os.environ.get("QONDUCTOR_NAMESPACE", "default")
    workflow_ref = os.environ.get("QONDUCTOR_WORKFLOW_NAME", cfg.get("workflowRef", ""))
    step_id = os.environ.get("QONDUCTOR_STEP_ID", "qaoa_spsa_driver")
    client = client or K8sClient(mode=mode)

    logical_id = cfg.get("logicalCircuitId") or cfg.get("circuit_id")
    circuit_qasm = cfg.get("circuitQasm") or cfg.get("circuit_qasm", "")
    if not circuit_qasm and cfg.get("qasmPath"):
        with open(cfg["qasmPath"], encoding="utf-8") as fh:
            circuit_qasm = fh.read()
    if not logical_id or not circuit_qasm:
        raise ValueError("QAOA config requires logicalCircuitId and circuitQasm")

    parameter_names = cfg.get("parameterNames") or cfg.get("parameter_names") or []
    qubits = int(cfg.get("qubits") or cfg.get("num_qubits") or 12)
    shots = int(cfg.get("shots", 1024))
    max_iterations = int(os.environ.get("R1_ITERATIONS", cfg.get("maxIterations", 200)))
    priority = cfg.get("priority", "balanced")
    edges = cfg.get("edges") or [list(edge) for edge in DEFAULT_QAOA_EDGES]
    timeout_s = float(cfg.get("quantumTimeoutSeconds", DEFAULT_QUANTUM_TIMEOUT_SECONDS))
    poll_s = float(cfg.get("pollSeconds", 2.0))

    if not parameter_names:
        parameter_names = [f"theta_{i}" for i in range(4)]

    theta = initialize_parameters(len(parameter_names))
    best_theta = list(theta)
    best_objective = math.inf
    rng = random.Random(int(cfg.get("seed", 12345)))
    execution_backend = os.environ.get(
        "QONDUCTOR_EXECUTION_BACKEND", "aer"
    ).strip().lower()
    offline_replay = execution_backend == "offline-replay"
    legacy_rng = legacy_c_random(int(cfg.get("seed", 12345)))
    pinned_qpu = ""
    history = []
    callback_server = QuantumResultCallbackServer.from_env(mode)

    for iteration in range(max_iterations):
        a = 0.18 / math.pow(float(iteration + 1), 0.602)
        c = 0.12 / math.pow(float(iteration + 1), 0.101)
        if offline_replay and pinned_qpu:
            plus_bindings, minus_bindings = offline_parameter_pair(
                logical_id=logical_id,
                qpu_name=pinned_qpu,
                iteration=iteration,
                parameter_names=parameter_names,
                shots=shots,
            )
            theta = [
                0.5 * (plus_bindings[name] + minus_bindings[name])
                for name in parameter_names
            ]
            delta = [
                1 if plus_bindings[name] > minus_bindings[name] else -1
                for name in parameter_names
            ]
        elif offline_replay:
            delta = [
                -1 if next(legacy_rng) < 0.5 else 1
                for _ in parameter_names
            ]
            theta_plus = [theta[i] + c * delta[i] for i in range(len(theta))]
            theta_minus = [theta[i] - c * delta[i] for i in range(len(theta))]
            plus_bindings = dict(zip(parameter_names, theta_plus))
            minus_bindings = dict(zip(parameter_names, theta_minus))
        else:
            delta = [-1 if rng.random() < 0.5 else 1 for _ in parameter_names]
            theta_plus = [theta[i] + c * delta[i] for i in range(len(theta))]
            theta_minus = [theta[i] - c * delta[i] for i in range(len(theta))]
            plus_bindings = dict(zip(parameter_names, theta_plus))
            minus_bindings = dict(zip(parameter_names, theta_minus))
        plus_qj = submit_quantum_eval(
            client,
            workflow_ref=workflow_ref,
            step_id=step_id,
            logical_circuit_id=logical_id,
            circuit_qasm=circuit_qasm,
            parameter_bindings=plus_bindings,
            qubits=qubits,
            shots=shots,
            priority=priority,
            iteration=iteration,
            eval_label="plus",
            preferred_qpu=pinned_qpu,
            result_callback=callback_server,
            namespace=namespace,
        )
        plus_result = None
        if offline_replay:
            plus_result = wait_for_quantum_result(
                client, plus_qj["metadata"]["name"],
                timeout_s=timeout_s, poll_s=poll_s,
                callback_server=callback_server,
            )
            if not pinned_qpu:
                pinned_qpu = quantum_job_assigned_qpu(
                    client, plus_qj["metadata"]["name"]
                )
                database_plus, minus_bindings = offline_parameter_pair(
                    logical_id=logical_id,
                    qpu_name=pinned_qpu,
                    iteration=iteration,
                    parameter_names=parameter_names,
                    shots=shots,
                )
                if database_plus != plus_bindings:
                    raise RuntimeError(
                        "offline driver parameters do not match the database "
                        "trajectory at iteration 0"
                    )

        minus_qj = submit_quantum_eval(
            client,
            workflow_ref=workflow_ref,
            step_id=step_id,
            logical_circuit_id=logical_id,
            circuit_qasm=circuit_qasm,
            parameter_bindings=minus_bindings,
            qubits=qubits,
            shots=shots,
            priority=priority,
            iteration=iteration,
            eval_label="minus",
            preferred_qpu=pinned_qpu,
            result_callback=callback_server,
            namespace=namespace,
        )
        if plus_result is None:
            plus_result = wait_for_quantum_result(
                client, plus_qj["metadata"]["name"],
                timeout_s=timeout_s, poll_s=poll_s,
                callback_server=callback_server,
            )
        minus_result = wait_for_quantum_result(
            client, minus_qj["metadata"]["name"],
            timeout_s=timeout_s, poll_s=poll_s,
            callback_server=callback_server,
        )

        avg_plus = counts_average(plus_result, edges, qubits)
        avg_minus = counts_average(minus_result, edges, qubits)
        objective_plus = -avg_plus
        objective_minus = -avg_minus
        if not math.isfinite(objective_plus) or not math.isfinite(objective_minus):
            raise RuntimeError(f"invalid objective at iteration {iteration}")

        center_objective = 0.5 * (objective_plus + objective_minus)
        if center_objective < best_objective:
            best_objective = center_objective
            best_theta = list(theta)

        for i in range(len(theta)):
            grad = (objective_plus - objective_minus) / (2.0 * c * delta[i])
            theta[i] -= a * grad
        theta = wrap_angles(theta)

        entry = {
            "iteration": iteration,
            "objective": center_objective,
            "objective_plus": objective_plus,
            "objective_minus": objective_minus,
            "theta": list(theta),
        }
        history.append(entry)
        print(json.dumps({"event": "qaoa_iteration", **entry}))

    summary = {
        "best_objective": best_objective,
        "best_theta": best_theta,
        "iterations": max_iterations,
        "history": history,
    }
    print(json.dumps({"event": "qaoa_complete", **summary}))
    if callback_server is not None:
        callback_server.close_after_fallback_drain()
    return summary
