apiVersion: qonductor.io/v1
kind: HybridWorkflow
metadata:
  name: pq-001-grover-no-ancilla-2-20260720095944-b4d2161
  namespace: default
  labels:
    app: qonductor
    algorithm: grover-no-ancilla
    converted_from: qslurm_workloads
spec:
  workflowImageRef: 9e25265eaf9f
  priority: balanced
  maxRetries: 3
  containers: []
  scheduling:
    classicalPolicy: FilterScore
    quantumPolicy: NSGA2
    schedulingInterval: 30
    schedulingThreshold: 1
  errorMitigation:
    enabled: false
    stackedTechniques: []
  workflowInputs:
    quantum:
      logicalCircuitId: grover-noancilla_indep_qiskit_2
      qasmPath: /home/reol/Qonductor-SC25/workflow/pure_quantum/grover_no_ancilla/grover-noancilla_indep_qiskit_2.qasm3
      circuitQasm: '// Benchmark was created by MQT Bench on 2024-03-19

        // For more information about MQT Bench, please visit https://www.cda.cit.tum.de/mqtbench/

        // MQT Bench version: 1.1.0

        // Qiskit version: 1.0.2

        // Used Gate Set: [''id'', ''rz'', ''sx'', ''x'', ''cx'', ''measure'', ''barrier'']


        OPENQASM 3.0;

        include "stdgates.inc";

        qubit[1] q;

        qubit[1] flag;

        bit[2] meas;

        rz(pi/2) q[0];

        sx q[0];

        rz(pi/2) q[0];

        x flag[0];

        barrier q[0],flag[0];

        meas[0] = measure q[0];

        meas[1] = measure flag[0];

        '
      circuitFormat: qasm3
      qubits: 2
      shots: 128
      priority: balanced
      source:
        qslurmSource: qslurm_workloads/pure_quantum/grover_no_ancilla/spec_2.json
        workloadDir: /home/reol/Qonductor-SC25/workflow/pure_quantum/grover_no_ancilla
        spec: /home/reol/Qonductor-SC25/workflow/pure_quantum/grover_no_ancilla/spec_2.json
