apiVersion: qonductor.io/v1
kind: HybridWorkflow
metadata:
  name: pq-053-w-state-2-20260722152725-c9def8a
  namespace: default
  labels:
    app: qonductor
    algorithm: w-state
    converted_from: qslurm_workloads
spec:
  workflowImageRef: 'c0e48db741a6'
  priority: balanced
  maxRetries: 3
  containers: []
  scheduling:
    classicalPolicy: FilterScore
    quantumPolicy: NSGA2
    schedulingInterval: 30
    schedulingThreshold: 1
  errorMitigation:
    enabled: false
    stackedTechniques: []
  workflowInputs:
    quantum:
      logicalCircuitId: wstate_indep_qiskit_2
      qasmPath: /home/reol/Qonductor-SC25/workflow/pure_quantum/w_state/wstate_indep_qiskit_2.qasm3
      circuitQasm: '// Benchmark was created by MQT Bench on 2024-03-19

        // For more information about MQT Bench, please visit https://www.cda.cit.tum.de/mqtbench/

        // MQT Bench version: 1.1.0

        // Qiskit version: 1.0.2

        // Used Gate Set: [''id'', ''rz'', ''sx'', ''x'', ''cx'', ''measure'', ''barrier'']


        OPENQASM 3.0;

        include "stdgates.inc";

        qubit[2] q;

        bit[2] meas;

        sx q[0];

        rz(pi/4) q[0];

        sx q[0];

        x q[1];

        cx q[1],q[0];

        sx q[0];

        rz(pi/4) q[0];

        sx q[0];

        cx q[0],q[1];

        barrier q[0],q[1];

        meas[0] = measure q[0];

        meas[1] = measure q[1];

        '
      circuitFormat: qasm3
      qubits: 2
      shots: 1024
      priority: balanced
      source:
        qslurmSource: qslurm_workloads/pure_quantum/w_state/spec_2.json
        workloadDir: /home/reol/Qonductor-SC25/workflow/pure_quantum/w_state
        spec: /home/reol/Qonductor-SC25/workflow/pure_quantum/w_state/spec_2.json
